name: "Login to Nexus Docker"
description: "Login to Nexus Docker"

inputs:
  username:
    description: "Username for image registry"
    required: true
  password:
    description: "Password for image registry"
    required: true
  registry:
    description: "Domain URL to login"
    required: true
  registry_push_port:
    description: "Port to login to push images"
    required: false
    default: "5000"

runs:
  using: "composite"
  steps:
    - name: Login to Nexus Docker
      uses: docker/login-action@v3
      with:
        registry: ${{inputs.registry}}
        username: ${{inputs.username}}
        password: ${{inputs.password}}
    - name: Login to Nexus Docker to PUSH
      uses: docker/login-action@v3
      with:
        registry: ${{inputs.registry}}:${{inputs.registry_push_port}}
        username: ${{inputs.username}}
        password: ${{inputs.password}}