name: "Login to Nexus Docker"
description: "Login to Nexus Docker"

inputs:
  registry_username:
    description: "Username for image registry"
    required: true
  registry_password:
    description: "Password for image registry"
    required: true
  registry_domain:
    description: "Domain URL to login"
    required: true
  registry_domain_push_port:
    description: "Port to login to push images"
    required: false
    default: "5000"

runs:
  using: "composite"
  steps:
    - name: Login to Nexus Docker
      uses: docker/login-action@v3
      with:
        registry: ${{ env.registry_domain_push_port }}
        username: ${{inputs.registry_username}}
        password: ${{inputs.registry_password}}
    - name: Login to Nexus Docker to PUSH
      uses: docker/login-action@v3
      with:
        registry: ${{inputs.registry_domain_push_port}}:${{inputs.registry_domain_push_port}}
        username: ${{inputs.registry_username}}
        password: ${{inputs.registry_password}}